version: "3.9"

services:
  api:
    image: golang:1.21-bullseye
    ports:
      - 7000:7000
    volumes:
      - ./api:/go/src/app
    working_dir: /go/src/app
    command: bash -c "go build -o main . && ./main"
    environment:
      TZ: America/Mexico_City
    depends_on:
      - db
  db:
    image: postgres:bullseye
    ports:
      - 5432:5432
    volumes:
      - ./db:/var/lib/postgresql/data
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    environment:
      TZ: America/Mexico_City
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres